### ISSUE TITLE
Meteor test crashes on a specific app

### ISSUE THREAD

**Issue by tophsic** [elidoran/cosmos-browserify#48]
Hi,

I run a Meteor application (1.3.5.1) with node 6.2.2. I got following error running `meteor test --driver-package practicalmeteor:mocha` command:

``` bash
[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
=> Meteor 1.4.1.1 is available. Update this project with 'meteor update'.
=> Errors prevented startup:                  

   While processing files with cosmos:browserify (for target web.browser):
   packages/CosmosBrowserify/plugin/browserify.coffee:254:29: Object [object Object] has no method 'existsSync'
   at BrowserifyPlugin.buildErrorMessage (packages/CosmosBrowserify/plugin/browserify.coffee:254:29)
   at BrowserifyPlugin.compileOneFile (packages/CosmosBrowserify/plugin/browserify.coffee:196:10)
   at multi-file-caching-compiler.js:115:45
   at multi-file-caching-compiler.js:144:68
   at
   /home/christophe/.meteor/packages/cosmos_browserify/.0.10.0.1i0wplk++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/node_modules/meteor/caching-compiler/caching-compiler/node_modules/async/lib/async.js:182:20
   at replenish
   (/home/christophe/.meteor/packages/cosmos_browserify/.0.10.0.1i0wplk++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/node_modules/meteor/caching-compiler/caching-compiler/node_modules/async/lib/async.js:317:21)
   at
   /home/christophe/.meteor/packages/cosmos_browserify/.0.10.0.1i0wplk++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/node_modules/meteor/caching-compiler/caching-compiler/node_modules/async/lib/async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (/home/christophe/.meteor/packages/cosmos_browserify/.0.10.0.1i0wplk++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/node_modules/meteor/caching-compiler/caching-compiler/node_modules/async/lib/async.js:221:35)
   at BrowserifyPlugin.processFilesForTarget (multi-file-caching-compiler.js:95:11)
```

I have another app which does not have this problem. I don't know how to find the issue on my project. Any idea ?

**Comment by tophsic** [comment]
Gasp, I should search more before posting. I missed a `meteor npm install` to install correctly npm dependencies.
