### ISSUE TITLE
TypeError: global.XMLHttpRequest is not a function

### ISSUE THREAD

**Issue by TechplexEngineer** [elidoran/cosmos-browserify#50]
I'm trying to use cosmos:browserify to bundle [softap-setup-js which supports browserify](https://github.com/spark/softap-setup-js#running-in-the-browser).

I seem to be getting an error about XMLHttpRequest not being a function. any thoughts?

I'm using Meteor 1.5.1 and cosmos:browserify@0.10.0

```
W20170810-22:36:40.955(-4)? (STDERR) /home/techplex/.meteor/packages/meteor-tool/.1.5.1.bag82p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170810-22:36:40.957(-4)? (STDERR) 						throw(ex);
W20170810-22:36:40.960(-4)? (STDERR) 						^
W20170810-22:36:40.961(-4)? (STDERR) 
W20170810-22:36:40.962(-4)? (STDERR) TypeError: global.XMLHttpRequest is not a function
W20170810-22:36:40.964(-4)? (STDERR)     at Object.<anonymous> (../../../.meteor/packages/cosmos_browserify/.0.10.0.17x0xtt++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/node_modules/meteor/CosmosBrowserify/CosmosBrowserify/node_modules/browserify/node_modules/stream-http/lib/capability.js:9:1)
W20170810-22:36:40.965(-4)? (STDERR)     at Object.224 (../../../.meteor/packages/cosmos_browserify/.0.10.0.17x0xtt++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/node_modules/meteor/CosmosBrowserify/CosmosBrowserify/node_modules/browserify/node_modules/stream-http/lib/capability.js:41:1)
W20170810-22:36:40.965(-4)? (STDERR)     at s (../../../.meteor/packages/cosmos_browserify/.0.10.0.17x0xtt++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/node_modules/meteor/CosmosBrowserify/CosmosBrowserify/node_modules/browserify/node_modules/browser-pack/_prelude.js:1:1)
W20170810-22:36:40.966(-4)? (STDERR)     at ../../../.meteor/packages/cosmos_browserify/.0.10.0.17x0xtt++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/node_modules/meteor/CosmosBrowserify/CosmosBrowserify/node_modules/browserify/node_modules/browser-pack/_prelude.js:1:1
W20170810-22:36:40.967(-4)? (STDERR)     at Object.<anonymous> (../../../.meteor/packages/cosmos_browserify/.0.10.0.17x0xtt++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/node_modules/meteor/CosmosBrowserify/CosmosBrowserify/node_modules/browserify/node_modules/stream-http/lib/request.js:2:1)
W20170810-22:36:40.968(-4)? (STDERR)     at Object.225../capability (../../../.meteor/packages/cosmos_browserify/.0.10.0.17x0xtt++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/node_modules/meteor/CosmosBrowserify/CosmosBrowserify/node_modules/browserify/node_modules/stream-http/lib/request.js:279:1)
W20170810-22:36:40.968(-4)? (STDERR)     at s (../../../.meteor/packages/cosmos_browserify/.0.10.0.17x0xtt++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/node_modules/meteor/CosmosBrowserify/CosmosBrowserify/node_modules/browserify/node_modules/browser-pack/_prelude.js:1:1)
W20170810-22:36:40.969(-4)? (STDERR)     at ../../../.meteor/packages/cosmos_browserify/.0.10.0.17x0xtt++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/node_modules/meteor/CosmosBrowserify/CosmosBrowserify/node_modules/browserify/node_modules/browser-pack/_prelude.js:1:1
W20170810-22:36:40.970(-4)? (STDERR)     at Object.<anonymous> (../../../.meteor/packages/cosmos_browserify/.0.10.0.17x0xtt++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/node_modules/meteor/CosmosBrowserify/CosmosBrowserify/node_modules/browserify/node_modules/stream-http/index.js:1:1)
W20170810-22:36:40.971(-4)? (STDERR)     at Object.223../lib/request (../../../.meteor/packages/cosmos_browserify/.0.10.0.17x0xtt++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/node_modules/meteor/CosmosBrowserify/CosmosBrowserify/node_modules/browserify/node_modules/stream-http/index.js:79:1)

```

**Comment by elidoran** [comment]
You shouldn't need to use Browserify with Meteor 1.5.1. Meteor has been supporting npm packages for a while now. You can install the package into your app and import it into client/server code and Meteor will take care of it.

Check out the [Meteor Guide](https://guide.meteor.com/using-npm-packages.html) explanation for using npm packages.

As for the error, have you checked to see if `global.XMLHttpRequest` is null or not a function?

**Comment by TechplexEngineer** [comment]
For my future googling self, be sure that the softap.browserify.js file is only loaded on the client as XMLHttpRequest is not available via nodeJs.

**Comment by elidoran** [comment]
Indeed, it's a browser tool from the early days of AJAX.

Server side there are better ways to make client requests, in node and pretty much every major server side language. :)
